# Generated by Django 5.0.6 on 2024-06-09 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_contactform_created_at_contactform_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flan",
            old_name="updated_at",
            new_name="modified_at",
        ),
    ]
