# Generated by Django 5.0.6 on 2024-06-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_client_delete_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.CharField(default="Dirección predeterminada", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="birth_date",
            field=models.DateField(default="1930-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="password",
            field=models.CharField(default="defaultpassword", max_length=15),
            preserve_default=False,
        ),
    ]
