# Generated by Django 5.0.6 on 2024-06-10 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_rename_updated_at_flan_modified_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                (
                    "email",
                    models.EmailField(default="cliente@cliente.cl", max_length=50),
                ),
                (
                    "age",
                    models.IntegerField(
                        default=18,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                ("subject", models.CharField(default="", max_length=200)),
                ("message", models.TextField(default="", max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
    ]
