# Generated by Django 5.0.6 on 2024-06-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_client_address_client_birth_date_client_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="password",
            field=models.CharField(default="defaultpassword", max_length=128),
        ),
    ]
